name: Build localization
on:
  push:
  pull_request:

jobs:
  localizator:
    name: Build language resourses
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - name: Start process
        run: cd localization && ./create-undefs.pl && cd ..
      - name: Copy files to repo
        uses: test-room-7/action-update-file@v1
        with:
           file-path: |
             localization/json/*.json
             localization/www/*.*
             localization/UNDEF_LANG_*.h
           commit-msg: Update language resources
           github-token: ${{ secrets.GITHUB_TOKEN }}
           
